version: "3"

services:
  node-explorer:
    image: prom/node-exporter
    command: bash -c '-collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"'
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  prometheus:
    image: prom/prometheus:v1.4.1
    ports:
      - "9090:9090"
    deploy:
      mode: global
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

  cadvisor:
    image: google/cadvisor:v0.24.0
    ports:
      - "8080:8080"
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "3000:3000"
