apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        volumeMounts:
        - name: registry-path
          mountPath: /var/lib/registry
      volumes:
      - name: registry-path
        hostPath:
          path: /var/lib/registry
---
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
spec:
  selector:
    app: kube-registry
  ports:
  - port: 5000
  type: NodePort
