version: '2'
services:
  jenkins:
    image: roicostas/docker-course-jenkins
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/jenkins_home:/var/jenkins_home
#    - /tmp/jenkins:/var/jenkins_home
    network_mode: host
  registry:
    image: registry:2
    ports:
    - "5000:5000"    
